name: Translation Sync

on:
  pull_request:
    types: [closed, labeled]

jobs:
  sync-translation:
    # Run on merge (production) OR when test-translation label added (test mode)
    if: |
      (github.event.pull_request.merged == true) ||
      (github.event.action == 'labeled' && github.event.label.name == 'test-translation')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v4
        with:
          repository: QuantEcon/action-translation-sync
          path: action
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd action
          npm ci
      
      - name: Determine mode
        id: mode
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "mode=production" >> $GITHUB_OUTPUT
            echo "commit_sha=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_OUTPUT
            echo "🚀 Running in PRODUCTION mode (merged PR)"
          else
            echo "mode=test" >> $GITHUB_OUTPUT
            echo "commit_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            echo "🧪 Running in TEST mode (test-translation label)"
          fi
      
      - name: Run translation sync
        with:
          target-repo: ${{ github.repository }}.zh-cn
          target-language: zh-cn
          source-language: en
          docs-folder: '.'
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-mode: ${{ steps.mode.outputs.mode == 'test' }}
        uses: ./action
